services:
  dev:
    build:
      dockerfile: ./dev.Dockerfile
    volumes:
      # Mount source files
      - .:/app
      # Mount pocketbase database volume
      - pocketbase-data:/pb/pb_data
    ports:
      - "8080:8080" # Pocketbase
      - "8000:8000" # React
    working_dir: "/app"
    command: sleep infinity

volumes:
  redash-data:
  pocketbase-data:
